### ISSUE TITLE
$NVIM_LISTEN_ADDRESS will be removed in Nvim 0.8

### ISSUE THREAD

**Issue by justinmk** [glacambre/ileum#1]
https://github.com/neovim/neovim/pull/11009 (Nvim 0.8+) will change Nvim so that $NVIM_LISTEN_ADDRESS is _not_ passed to child processes.  After that, the correct way to detect a "host" or "parent" Nvim is to check for $NVIM env var: this means the current process is a child of Nvim.

The old $NVIM_LISTEN_ADDRESS env var had conflicting purposes as both a parameter ("the current process should _listen on_ this address") and a descriptor ("the current process is a _child of_ this address").

**Comment by glacambre** [comment]
Thanks a lot for notifying me, Justin!
